mongodb_uri = "mongodb+srv://geminiadvanced2025:Z3w9cEHBZURgzQ4A@cluster0.ojrbk.mongodb.net/huggingface_models?retryWrites=true&w=majority&appName=Cluster0"
mongodb_database = "model_metadata"
mongodb_collection = "models"